#############################################################################
# Makefile for building: TestTask
# Generated by qmake (2.01a) (Qt 4.8.3) on: Mon Mar 25 23:26:41 2013
# Project:  TestTask.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile TestTask.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Ivlc1 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/var/www/testlab.mr_che/TestTask/libvlc.a -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		networkwrapper.cpp \
		json.cpp \
		vlcwidget.cpp \
		form.cpp moc_networkwrapper.cpp \
		moc_vlcwidget.cpp \
		moc_form.cpp
OBJECTS       = main.o \
		networkwrapper.o \
		json.o \
		vlcwidget.o \
		form.o \
		moc_networkwrapper.o \
		moc_vlcwidget.o \
		moc_form.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TestTask.pro
QMAKE_TARGET  = TestTask
DESTDIR       = 
TARGET        = TestTask

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_form.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TestTask.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile TestTask.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile TestTask.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TestTask1.0.0 || $(MKDIR) .tmp/TestTask1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TestTask1.0.0/ && $(COPY_FILE) --parents networkwrapper.h json.h vlcwidget.h form.h .tmp/TestTask1.0.0/ && $(COPY_FILE) --parents main.cpp networkwrapper.cpp json.cpp vlcwidget.cpp form.cpp .tmp/TestTask1.0.0/ && $(COPY_FILE) --parents form.ui .tmp/TestTask1.0.0/ && (cd `dirname .tmp/TestTask1.0.0` && $(TAR) TestTask1.0.0.tar TestTask1.0.0 && $(COMPRESS) TestTask1.0.0.tar) && $(MOVE) `dirname .tmp/TestTask1.0.0`/TestTask1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TestTask1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_networkwrapper.cpp moc_vlcwidget.cpp moc_form.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_networkwrapper.cpp moc_vlcwidget.cpp moc_form.cpp
moc_networkwrapper.cpp: json.h \
		networkwrapper.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) networkwrapper.h -o moc_networkwrapper.cpp

moc_vlcwidget.cpp: networkwrapper.h \
		json.h \
		form.h \
		vlc1/vlc/vlc.h \
		vlc1/vlc/libvlc_structures.h \
		vlc1/vlc/libvlc.h \
		vlc1/vlc/libvlc_media.h \
		vlc1/vlc/libvlc_media_player.h \
		vlc1/vlc/libvlc_media_list.h \
		vlc1/vlc/libvlc_media_list_view.h \
		vlc1/vlc/libvlc_media_list_player.h \
		vlc1/vlc/libvlc_media_library.h \
		vlc1/vlc/libvlc_media_discoverer.h \
		vlc1/vlc/libvlc_events.h \
		vlc1/vlc/libvlc_vlm.h \
		vlc1/vlc/deprecated.h \
		vlcwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) vlcwidget.h -o moc_vlcwidget.cpp

moc_form.cpp: form.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) form.h -o moc_form.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_form.h
compiler_uic_clean:
	-$(DEL_FILE) ui_form.h
ui_form.h: form.ui
	/usr/bin/uic-qt4 form.ui -o ui_form.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp vlcwidget.h \
		networkwrapper.h \
		json.h \
		form.h \
		vlc1/vlc/vlc.h \
		vlc1/vlc/libvlc_structures.h \
		vlc1/vlc/libvlc.h \
		vlc1/vlc/libvlc_media.h \
		vlc1/vlc/libvlc_media_player.h \
		vlc1/vlc/libvlc_media_list.h \
		vlc1/vlc/libvlc_media_list_view.h \
		vlc1/vlc/libvlc_media_list_player.h \
		vlc1/vlc/libvlc_media_library.h \
		vlc1/vlc/libvlc_media_discoverer.h \
		vlc1/vlc/libvlc_events.h \
		vlc1/vlc/libvlc_vlm.h \
		vlc1/vlc/deprecated.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

networkwrapper.o: networkwrapper.cpp networkwrapper.h \
		json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networkwrapper.o networkwrapper.cpp

json.o: json.cpp json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json.o json.cpp

vlcwidget.o: vlcwidget.cpp vlcwidget.h \
		networkwrapper.h \
		json.h \
		form.h \
		vlc1/vlc/vlc.h \
		vlc1/vlc/libvlc_structures.h \
		vlc1/vlc/libvlc.h \
		vlc1/vlc/libvlc_media.h \
		vlc1/vlc/libvlc_media_player.h \
		vlc1/vlc/libvlc_media_list.h \
		vlc1/vlc/libvlc_media_list_view.h \
		vlc1/vlc/libvlc_media_list_player.h \
		vlc1/vlc/libvlc_media_library.h \
		vlc1/vlc/libvlc_media_discoverer.h \
		vlc1/vlc/libvlc_events.h \
		vlc1/vlc/libvlc_vlm.h \
		vlc1/vlc/deprecated.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vlcwidget.o vlcwidget.cpp

form.o: form.cpp form.h \
		ui_form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form.o form.cpp

moc_networkwrapper.o: moc_networkwrapper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networkwrapper.o moc_networkwrapper.cpp

moc_vlcwidget.o: moc_vlcwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vlcwidget.o moc_vlcwidget.cpp

moc_form.o: moc_form.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form.o moc_form.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

